### ISSUE TITLE
Missing v1 release

### ISSUE THREAD

**Issue by patrick-stephens** [stoat-dev/kubernetes-log-export-action#2]
Following the docs leads to an error as there is no published `v1` release for this action:

```
      - name: Dump Kubernetes Logs
        if: always()
        uses: stoat-dev/kubernetes-log-export-action@v1
        with:
          namespaces: default,kube-system
          show_timestamps: 'true'
          output_dir: kube-logs-output
```

```
Error: Unable to resolve action `stoat-dev/kubernetes-log-export-action@v1`, unable to find version `v1`
```
