### ISSUE TITLE
Missing kubelogs.sh file

### ISSUE THREAD

**Issue by patrick-stephens** [stoat-dev/kubernetes-log-export-action#3]
Using the @main version - see #2:
```yaml

      - name: Dump Kubernetes Logs
        if: always()
        uses: stoat-dev/kubernetes-log-export-action@main
        with:
          namespaces: default,kube-system
          show_timestamps: 'true'
          output_dir: kube-logs-output
```

I get the following error:
```
...
Download action repository 'stoat-dev/kubernetes-log-export-action@main' (SHA:4bee2c463b03f408d7e7651dc9c31d93ba2689e9)
...
Run stoat-dev/kubernetes-log-export-action@main
  with:
    namespaces: default,kube-system
    show_timestamps: true
    output_dir: kube-logs-output
Running kubectl scripts...
Dumping logs for namespace: default
Error: Unable to locate executable file: /home/runner/work/core-images/core-images/kubelogs.sh. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
